# Generated by Django 6.0.7 on 2026-07-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم المشارك')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('rank', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('result', models.CharField(max_length=100, verbose_name='النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشارك',
                'verbose_name_plural': 'المشاركون',
                'ordering': ['rank', 'participant_id'],
            },
        ),
    ]
