# Generated by Django 6.0.7 on 2026-07-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.CharField(db_index=True, max_length=14, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='النتيجة'),
        ),
    ]
