# Generated by Django 6.0.7 on 2026-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_participant_participant_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': [models.OrderBy(models.F('rank'), nulls_last=True), 'participant_id'], 'verbose_name': 'مشارك', 'verbose_name_plural': 'المشاركون'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الترتيب'),
        ),
    ]
