# Generated by Django 6.0.7 on 2026-09-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participant_sheikh_name_alter_participant_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(default='', max_length=15, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='sheikh_name',
            field=models.CharField(max_length=200, verbose_name='اسم الشيخ المحفظ'),
        ),
    ]
