# Generated by Django 6.0.7 on 2026-09-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_participant_phone_alter_participant_sheikh_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='parts_count',
            field=models.PositiveIntegerField(choices=[(1, '1 جزء'), (2, '2 جزء'), (3, '3 جزء'), (4, '4 جزء'), (5, '5 جزء'), (6, '6 جزء'), (7, '7 جزء'), (8, '8 جزء'), (9, '9 جزء'), (10, '10 جزء'), (11, '11 جزء'), (12, '12 جزء'), (13, '13 جزء'), (14, '14 جزء'), (15, '15 جزء'), (16, '16 جزء'), (17, '17 جزء'), (18, '18 جزء'), (19, '19 جزء'), (20, '20 جزء'), (21, '21 جزء'), (22, '22 جزء'), (23, '23 جزء'), (24, '24 جزء'), (25, '25 جزء'), (26, '26 جزء'), (27, '27 جزء'), (28, '28 جزء'), (29, '29 جزء'), (30, '30 جزء')], default=1, verbose_name='عدد الأجزاء'),
            preserve_default=False,
        ),
    ]
