# Generated by Django 6.0.7 on 2026-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_participant_parts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registration_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='رقم الاستمارة'),
        ),
    ]
