# Generated by Django 6.0.7 on 2026-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_participant_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-season_year', models.OrderBy(models.F('rank'), nulls_last=True), 'participant_id'], 'verbose_name': 'مشارك', 'verbose_name_plural': 'المشاركون'},
        ),
        migrations.AddField(
            model_name='participant',
            name='season_year',
            field=models.PositiveIntegerField(db_index=True, default=2026, verbose_name='سنة التسجيل'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.CharField(db_index=True, max_length=14, verbose_name='الرقم القومي'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('participant_id', 'season_year'), name='unique_participant_per_season'),
        ),
    ]
